# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/vivado/vivado.cache/wt [current_project]
set_property parent.project_path /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/vivado/vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/vivado/vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/testAsm/inst_rom.data
read_verilog -library xil_defaultlib {
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/defines.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/LLbit_reg.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/cp0_reg.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/ctrl.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/data_ram.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/div.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/ex.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/ex_mem.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/hilo_reg.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/id.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/id_ex.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/if_id.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/inst_rom.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/mem.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/mem_wb.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/openmips.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/openmips_min_sopc.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/pc_reg.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/regfile.v
  /home/fky/code/HDL/VIVADO_PROJECT/CH4-1-mips32/src/openmips_min_sopc_tb.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top openmips_min_sopc_tb -part xc7vx485tffg1157-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef openmips_min_sopc_tb.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file openmips_min_sopc_tb_utilization_synth.rpt -pb openmips_min_sopc_tb_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
